version: "3"
services:
  datadog:
    build: .
    environment:
     - DD_API_KEY
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro